# 站点配置文件

# base url 
# 网站URL
baseURL = "https://blog.fengzhao.pro"

# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"


################################################################################################# 
# theme主题
theme = "DoIt"

# themes directory主题目录
themesDir = "../.."

# 指定data目录。存放其他配置文件，通常为JSON、YAML或TOML格式。默认: data
dataDir = "data"


# 指定文章模板目录。默认：archetypes
# archetypeDir：

# 指定资源目录。存放需要Hugo Pipes处理的文件，比如需要编译的Sass或Less等。默认：assets
# assetDir：

# 指定内容目录。默认：content
contentDir = "content"
#################################################################################################


# website title
# 网站标题
title = "fengzhao's blog"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true

# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true

# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
