
# hugo.yaml：站点配置文件；
# languages.yaml：语言配置文件，多语言站点才需要用到；
# menus.zh.yaml：中文菜单配置文件，非多语言站点只需要menus.yaml即可；
# params.yaml：主题需要用到的参数配置文件；


baseURL = 'https://blog.fengzhao.pro'


# 默认语言代码
# config.toml: 站点主配置文件，里面的defaultContentLanguage要设置为zh，他会检索languages.<语言>.toml和menu.<语言>.toml两个配置。
defaultcontentlanguage = 'zh'

# 网站语言
languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'DoIt'

