baseURL = 'https://blog.fengzhao.pro'



# config.toml: 站点主配置文件，里面的defaultContentLanguage要设置为zh，他会检索languages.<语言>.toml和menu.<语言>.toml两个配置。
defaultcontentlanguage = 'zh'

languageCode = 'zh-cn'
title = 'My New Hugo Site'
theme = 'DoIt'


