[zh-cn]
  weight = 1
  title = "我的全新 Hugo 网站"
  # 网站语言, 仅在这里 CN 大写
  languageCode = "zh-cn"
  languageName = "简体中文"
  # 是否包括中日韩文字
  hasCJKLanguage = true   
[en]
  weight = 2
  title = "My New Hugo Site"
  languageCode = "en"
  languageName = "English"
