name: CI #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - main
  workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@v2.3.4 #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.140.1
          extended: true
      - name: Build
        run: hugo -D
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          EXTERNAL_REPOSITORY: fengzhao/hugo-blog # 注意要修改本处地址
          cname: blog.fengzhao.pro
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
